#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)/my-standard"

# Eyeball validation - should produce a few linting errors.
./vendor/bin/phpcs --standard=MyStandard poorly_formatted.php
